name: Link Preview App Deploy
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Copy Repo
        uses: actions/checkout@v3
      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install node modules
        run: npm i
      - name: Build app
        run: npm run build
      - name: FTP Upload
        uses: SamKirkland/FTP-Deploy-Action@4.3.2
        with:
          server: ${{secrets.FTP_HOST}}
          username: ${{secrets.FTP_UNAME}}
          password: ${{ secrets.FTP_PASS }}
          local-dir: ./build/